{"name": "Проверка появления ошибки при удалении курьера с неверным id", "status": "passed", "start": 1717357823605, "stop": 1717357823683, "uuid": "94ffe486-1f52-4574-95a0-381a7ffd8d7c", "historyId": "361a7a4c712e78c3b6f96ab7cd284c9f", "testCaseId": "361a7a4c712e78c3b6f96ab7cd284c9f", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_failed_delete_courier_with_wrong_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "msknbfb5654inb"}, {"name": "thread", "value": "17632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}