{"name": "Проверка появления ошибки при удалении курьера без id", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_delete_courier.TestDeleteCourier object at 0x00000205CCCD5460>\n\n    @allure.title('Проверка появления ошибки при удалении курьера без id')\n    @allure.description('Тест падает, т.к. приходит неверный код ответа')  # Проверила в Postman - 404 \"Not Found.\"\n    def test_failed_delete_courier_without_id(self):\n        delete_response = courier_api.delete_courier(urls.DELETE_COURIER_URL)\n>       assert (delete_response.status_code == 400 and\n                delete_response.json()['message'] == \"Недостаточно данных для удаления курьера\")\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_delete_courier.py:20: AssertionError"}, "description": "Тест падает, т.к. приходит неверный код ответа", "start": 1717357823532, "stop": 1717357823588, "uuid": "6fe9dbb2-f53d-4965-b317-c86e166e9479", "historyId": "0a6befc8c287e161727859681b3a01e6", "testCaseId": "0a6befc8c287e161727859681b3a01e6", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_failed_delete_courier_without_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "msknbfb5654inb"}, {"name": "thread", "value": "17632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}]}